[package]
name = "grpcrash"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
libafl = "0.16.1"
once_cell = "1.21.4"
prost = "0.14.4"
prost-reflect = "0.16.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
